FROM registry.suse.com/bci/golang:1.25@sha256:feeb8b4f66de0a8ba333ee6a3f0e97b4cefbaf638b2873b29fb270ab5ca8722b

ARG DAPPER_HOST_ARCH
ENV ARCH=${DAPPER_HOST_ARCH}

ENV DAPPER_RUN_ARGS --privileged
ENV DAPPER_ENV REPO TAG DRONE_TAG
ENV DAPPER_SOURCE /cli
ENV DAPPER_OUTPUT ./bin ./docs coverage.out
ENV DAPPER_DOCKER_SOCKET true

ENV GOLANGCI_LINT_VERSION=v2.11.4

WORKDIR ${DAPPER_SOURCE}
ENTRYPOINT ["./dapper/entry"]
CMD ["ci"]

RUN zypper update -y

RUN zypper -n install curl awk docker && \
    rm -rf /var/cache/zypp/*

RUN curl -fsSL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh -o /tmp/install.sh \
    && chmod +x /tmp/install.sh \
    && /tmp/install.sh -b /usr/local/bin ${GOLANGCI_LINT_VERSION}

# Docker Buildx: The docker version in dapper is too old to have buildx. Install it manually.
RUN curl -sSfLO https://github.com/docker/buildx/releases/download/v0.13.1/buildx-v0.13.1.linux-${ARCH} && \
    chmod +x buildx-v0.13.1.linux-${ARCH} && \
    mv buildx-v0.13.1.linux-${ARCH} /usr/local/bin/buildx

