FROM golangci/golangci-lint:v2.12.2@sha256:5cceeef04e53efe1470638d4b4b4f5ceefd574955ab3941b2d9a68a8c9ad5240 AS golangci-lint

FROM registry.suse.com/bci/golang:1.25@sha256:a086bf3003dd1d8124e77f2d8d4e9aa2e8a163f5e0399294ec515a714a3b8e0d

ARG DAPPER_HOST_ARCH
ENV ARCH=${DAPPER_HOST_ARCH}

ENV DAPPER_RUN_ARGS --privileged
ENV DAPPER_ENV REPO TAG DRONE_TAG
ENV DAPPER_SOURCE /cli
ENV DAPPER_OUTPUT ./bin ./docs coverage.out
ENV DAPPER_DOCKER_SOCKET true

WORKDIR ${DAPPER_SOURCE}
ENTRYPOINT ["./dapper/entry"]
CMD ["ci"]

RUN zypper update -y

RUN zypper -n install curl awk docker && \
    rm -rf /var/cache/zypp/*

# Copy golangci-lint binary from official image
COPY --from=golangci-lint /usr/bin/golangci-lint /usr/local/bin/golangci-lint

# Docker Buildx: The docker version in dapper is too old to have buildx. Install it manually.
RUN curl -sSfLO https://github.com/docker/buildx/releases/download/v0.13.1/buildx-v0.13.1.linux-${ARCH} && \
    chmod +x buildx-v0.13.1.linux-${ARCH} && \
    mv buildx-v0.13.1.linux-${ARCH} /usr/local/bin/buildx

