apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-preflight
  labels:
    app: longhorn-preflight
spec:
  selector:
    matchLabels:
      app: longhorn-preflight
  template:
    metadata:
      labels:
        app: longhorn-preflight
    spec:
      hostNetwork: true
      hostPID: true
      initContainers:
      - name: longhorn-preflight
        command:
        - longhorn-preflight
        - check
        image: longhornio/longhorn-cli:master-head
        securityContext:
          privileged: true
        env:
        - name: ENABLE_SPDK
          value: "true"
        - name: HUGEMEM
          value: "2048"
        - name: USERSPACE_DRIVER
          value: "vfio_pci"
        volumeMounts:
        - name: host
          mountPath: /host/
      containers:
      - name: sleep
        image: registry.k8s.io/pause:3.1
      volumes:
      - name: host
        hostPath:
          path: /
      - name: longhorn
  updateStrategy:
    type: RollingUpdate
