// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPackageManager creates a new instance of MockPackageManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackageManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackageManager {
	mock := &MockPackageManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPackageManager is an autogenerated mock type for the PackageManager type
type MockPackageManager struct {
	mock.Mock
}

type MockPackageManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackageManager) EXPECT() *MockPackageManager_Expecter {
	return &MockPackageManager_Expecter{mock: &_m.Mock}
}

// CheckModLoaded provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) CheckModLoaded(module string) error {
	ret := _mock.Called(module)

	if len(ret) == 0 {
		panic("no return value specified for CheckModLoaded")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(module)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPackageManager_CheckModLoaded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckModLoaded'
type MockPackageManager_CheckModLoaded_Call struct {
	*mock.Call
}

// CheckModLoaded is a helper method to define mock.On call
//   - module string
func (_e *MockPackageManager_Expecter) CheckModLoaded(module any) *MockPackageManager_CheckModLoaded_Call {
	return &MockPackageManager_CheckModLoaded_Call{Call: _e.mock.On("CheckModLoaded", module)}
}

func (_c *MockPackageManager_CheckModLoaded_Call) Run(run func(module string)) *MockPackageManager_CheckModLoaded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPackageManager_CheckModLoaded_Call) Return(err error) *MockPackageManager_CheckModLoaded_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPackageManager_CheckModLoaded_Call) RunAndReturn(run func(module string) error) *MockPackageManager_CheckModLoaded_Call {
	_c.Call.Return(run)
	return _c
}

// CheckPackageInstalled provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) CheckPackageInstalled(name string) (string, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CheckPackageInstalled")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPackageManager_CheckPackageInstalled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPackageInstalled'
type MockPackageManager_CheckPackageInstalled_Call struct {
	*mock.Call
}

// CheckPackageInstalled is a helper method to define mock.On call
//   - name string
func (_e *MockPackageManager_Expecter) CheckPackageInstalled(name any) *MockPackageManager_CheckPackageInstalled_Call {
	return &MockPackageManager_CheckPackageInstalled_Call{Call: _e.mock.On("CheckPackageInstalled", name)}
}

func (_c *MockPackageManager_CheckPackageInstalled_Call) Run(run func(name string)) *MockPackageManager_CheckPackageInstalled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPackageManager_CheckPackageInstalled_Call) Return(s string, err error) *MockPackageManager_CheckPackageInstalled_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPackageManager_CheckPackageInstalled_Call) RunAndReturn(run func(name string) (string, error)) *MockPackageManager_CheckPackageInstalled_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) Execute(envs []string, binary string, args []string, timeout time.Duration) (string, error) {
	ret := _mock.Called(envs, binary, args, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string, string, []string, time.Duration) (string, error)); ok {
		return returnFunc(envs, binary, args, timeout)
	}
	if returnFunc, ok := ret.Get(0).(func([]string, string, []string, time.Duration) string); ok {
		r0 = returnFunc(envs, binary, args, timeout)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func([]string, string, []string, time.Duration) error); ok {
		r1 = returnFunc(envs, binary, args, timeout)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPackageManager_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockPackageManager_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - envs []string
//   - binary string
//   - args []string
//   - timeout time.Duration
func (_e *MockPackageManager_Expecter) Execute(envs any, binary any, args any, timeout any) *MockPackageManager_Execute_Call {
	return &MockPackageManager_Execute_Call{Call: _e.mock.On("Execute", envs, binary, args, timeout)}
}

func (_c *MockPackageManager_Execute_Call) Run(run func(envs []string, binary string, args []string, timeout time.Duration)) *MockPackageManager_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPackageManager_Execute_Call) Return(s string, err error) *MockPackageManager_Execute_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPackageManager_Execute_Call) RunAndReturn(run func(envs []string, binary string, args []string, timeout time.Duration) (string, error)) *MockPackageManager_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceStatus provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) GetServiceStatus(name string) (string, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceStatus")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPackageManager_GetServiceStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceStatus'
type MockPackageManager_GetServiceStatus_Call struct {
	*mock.Call
}

// GetServiceStatus is a helper method to define mock.On call
//   - name string
func (_e *MockPackageManager_Expecter) GetServiceStatus(name any) *MockPackageManager_GetServiceStatus_Call {
	return &MockPackageManager_GetServiceStatus_Call{Call: _e.mock.On("GetServiceStatus", name)}
}

func (_c *MockPackageManager_GetServiceStatus_Call) Run(run func(name string)) *MockPackageManager_GetServiceStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPackageManager_GetServiceStatus_Call) Return(s string, err error) *MockPackageManager_GetServiceStatus_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPackageManager_GetServiceStatus_Call) RunAndReturn(run func(name string) (string, error)) *MockPackageManager_GetServiceStatus_Call {
	_c.Call.Return(run)
	return _c
}

// InstallPackage provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) InstallPackage(name string) (string, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for InstallPackage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPackageManager_InstallPackage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InstallPackage'
type MockPackageManager_InstallPackage_Call struct {
	*mock.Call
}

// InstallPackage is a helper method to define mock.On call
//   - name string
func (_e *MockPackageManager_Expecter) InstallPackage(name any) *MockPackageManager_InstallPackage_Call {
	return &MockPackageManager_InstallPackage_Call{Call: _e.mock.On("InstallPackage", name)}
}

func (_c *MockPackageManager_InstallPackage_Call) Run(run func(name string)) *MockPackageManager_InstallPackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPackageManager_InstallPackage_Call) Return(s string, err error) *MockPackageManager_InstallPackage_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPackageManager_InstallPackage_Call) RunAndReturn(run func(name string) (string, error)) *MockPackageManager_InstallPackage_Call {
	_c.Call.Return(run)
	return _c
}

// Modprobe provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) Modprobe(module string, opts ...string) (string, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(module, opts)
	} else {
		tmpRet = _mock.Called(module)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Modprobe")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) (string, error)); ok {
		return returnFunc(module, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...string) string); ok {
		r0 = returnFunc(module, opts...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = returnFunc(module, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPackageManager_Modprobe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modprobe'
type MockPackageManager_Modprobe_Call struct {
	*mock.Call
}

// Modprobe is a helper method to define mock.On call
//   - module string
//   - opts ...string
func (_e *MockPackageManager_Expecter) Modprobe(module any, opts ...any) *MockPackageManager_Modprobe_Call {
	return &MockPackageManager_Modprobe_Call{Call: _e.mock.On("Modprobe",
		append([]any{module}, opts...)...)}
}

func (_c *MockPackageManager_Modprobe_Call) Run(run func(module string, opts ...string)) *MockPackageManager_Modprobe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockPackageManager_Modprobe_Call) Return(s string, err error) *MockPackageManager_Modprobe_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPackageManager_Modprobe_Call) RunAndReturn(run func(module string, opts ...string) (string, error)) *MockPackageManager_Modprobe_Call {
	_c.Call.Return(run)
	return _c
}

// NeedReboot provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) NeedReboot() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NeedReboot")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPackageManager_NeedReboot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NeedReboot'
type MockPackageManager_NeedReboot_Call struct {
	*mock.Call
}

// NeedReboot is a helper method to define mock.On call
func (_e *MockPackageManager_Expecter) NeedReboot() *MockPackageManager_NeedReboot_Call {
	return &MockPackageManager_NeedReboot_Call{Call: _e.mock.On("NeedReboot")}
}

func (_c *MockPackageManager_NeedReboot_Call) Run(run func()) *MockPackageManager_NeedReboot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPackageManager_NeedReboot_Call) Return(b bool) *MockPackageManager_NeedReboot_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPackageManager_NeedReboot_Call) RunAndReturn(run func() bool) *MockPackageManager_NeedReboot_Call {
	_c.Call.Return(run)
	return _c
}

// RestartService provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) RestartService(name string) (string, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for RestartService")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPackageManager_RestartService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartService'
type MockPackageManager_RestartService_Call struct {
	*mock.Call
}

// RestartService is a helper method to define mock.On call
//   - name string
func (_e *MockPackageManager_Expecter) RestartService(name any) *MockPackageManager_RestartService_Call {
	return &MockPackageManager_RestartService_Call{Call: _e.mock.On("RestartService", name)}
}

func (_c *MockPackageManager_RestartService_Call) Run(run func(name string)) *MockPackageManager_RestartService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPackageManager_RestartService_Call) Return(s string, err error) *MockPackageManager_RestartService_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPackageManager_RestartService_Call) RunAndReturn(run func(name string) (string, error)) *MockPackageManager_RestartService_Call {
	_c.Call.Return(run)
	return _c
}

// StartPackageSession provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) StartPackageSession() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartPackageSession")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPackageManager_StartPackageSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartPackageSession'
type MockPackageManager_StartPackageSession_Call struct {
	*mock.Call
}

// StartPackageSession is a helper method to define mock.On call
func (_e *MockPackageManager_Expecter) StartPackageSession() *MockPackageManager_StartPackageSession_Call {
	return &MockPackageManager_StartPackageSession_Call{Call: _e.mock.On("StartPackageSession")}
}

func (_c *MockPackageManager_StartPackageSession_Call) Run(run func()) *MockPackageManager_StartPackageSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPackageManager_StartPackageSession_Call) Return(s string, err error) *MockPackageManager_StartPackageSession_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPackageManager_StartPackageSession_Call) RunAndReturn(run func() (string, error)) *MockPackageManager_StartPackageSession_Call {
	_c.Call.Return(run)
	return _c
}

// StartService provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) StartService(name string) (string, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for StartService")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPackageManager_StartService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartService'
type MockPackageManager_StartService_Call struct {
	*mock.Call
}

// StartService is a helper method to define mock.On call
//   - name string
func (_e *MockPackageManager_Expecter) StartService(name any) *MockPackageManager_StartService_Call {
	return &MockPackageManager_StartService_Call{Call: _e.mock.On("StartService", name)}
}

func (_c *MockPackageManager_StartService_Call) Run(run func(name string)) *MockPackageManager_StartService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPackageManager_StartService_Call) Return(s string, err error) *MockPackageManager_StartService_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPackageManager_StartService_Call) RunAndReturn(run func(name string) (string, error)) *MockPackageManager_StartService_Call {
	_c.Call.Return(run)
	return _c
}

// UninstallPackage provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) UninstallPackage(name string) (string, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for UninstallPackage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPackageManager_UninstallPackage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UninstallPackage'
type MockPackageManager_UninstallPackage_Call struct {
	*mock.Call
}

// UninstallPackage is a helper method to define mock.On call
//   - name string
func (_e *MockPackageManager_Expecter) UninstallPackage(name any) *MockPackageManager_UninstallPackage_Call {
	return &MockPackageManager_UninstallPackage_Call{Call: _e.mock.On("UninstallPackage", name)}
}

func (_c *MockPackageManager_UninstallPackage_Call) Run(run func(name string)) *MockPackageManager_UninstallPackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPackageManager_UninstallPackage_Call) Return(s string, err error) *MockPackageManager_UninstallPackage_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPackageManager_UninstallPackage_Call) RunAndReturn(run func(name string) (string, error)) *MockPackageManager_UninstallPackage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePackageList provides a mock function for the type MockPackageManager
func (_mock *MockPackageManager) UpdatePackageList() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UpdatePackageList")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPackageManager_UpdatePackageList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePackageList'
type MockPackageManager_UpdatePackageList_Call struct {
	*mock.Call
}

// UpdatePackageList is a helper method to define mock.On call
func (_e *MockPackageManager_Expecter) UpdatePackageList() *MockPackageManager_UpdatePackageList_Call {
	return &MockPackageManager_UpdatePackageList_Call{Call: _e.mock.On("UpdatePackageList")}
}

func (_c *MockPackageManager_UpdatePackageList_Call) Run(run func()) *MockPackageManager_UpdatePackageList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPackageManager_UpdatePackageList_Call) Return(s string, err error) *MockPackageManager_UpdatePackageList_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPackageManager_UpdatePackageList_Call) RunAndReturn(run func() (string, error)) *MockPackageManager_UpdatePackageList_Call {
	_c.Call.Return(run)
	return _c
}
