#!/bin/bash
set -e -x

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin

[ "$(uname)" != "Darwin" ] && LINKFLAGS="-extldflags -static -s"
CGO_ENABLED=0 go build -ldflags \
  "-X github.com/longhorn/longhorn-preflight/meta.Version=$VERSION \
   -X github.com/longhorn/longhorn-preflight/meta.GitCommit=$GITCOMMIT \
   -X github.com/longhorn/longhorn-preflight/meta.BuildDate=$BUILDDATE \
   $LINKFLAGS" -o bin/longhorn-preflight