#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

ARCH=${ARCH:-amd64}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

TAG=${TAG:-v`date -u +%Y%m%d`}
REPO=${REPO:-longhornio}
IMAGE=${IMAGE:-${REPO}/longhorn-preflight:${TAG}}

if [ ! -e ./bin/longhorn-preflight ]; then
    ./scripts/build
fi

# update base image to get latest changes
BASE_IMAGE=`grep FROM package/Dockerfile  | awk '{print $2}'`
docker pull ${BASE_IMAGE}

docker build -t ${IMAGE} -f package/Dockerfile .

echo Built ${IMAGE}

echo ${IMAGE} > ./bin/latest_image