#!/bin/bash
set -e

ROOT_DIR=$(cd "$(dirname "$0")"/.. && pwd)

ARCH=${ARCH:-amd64}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

TAG=${TAG:-v$(date -u +%Y%m%d)}
REPO=${REPO:-longhornio}
IMAGE=${IMAGE:-${REPO}/longhorn-cli:${TAG}}

source "${ROOT_DIR}/dapper/version"
cd "${ROOT_DIR}"

if [ ! -e ./bin/longhornctl ]; then
    ./dapper/build
fi

# Build image
buildx build --load -t ${IMAGE} -f package/Dockerfile .

echo Built "${IMAGE}"
# shellcheck disable=SC2086
echo ${IMAGE} > ./bin/latest_image
